### PR TITLE
Payment

### PR DESCRIPTION
**Pull request by SaraVieira**

### CODE REVIEW

**Comment by SaraVieira** [comment]
@alexluong I merged it into here  can you please take a look and see if it makes more sense?

**Comment by alexluong** [comment]
Hey! I checked out the code. It does make a lot more sense. Just a few questions:

- Just wondering why you're hardcoding the Stripe API keys in the functions instead of using environment variables?
- It seems like you tried `const info = require("../bookInfo")` but then reverted back. What's the issue with it?
- Lastly, I finally understand what you meant by using email and check Stripe to verify that they're a customer. However, I think it's not the most secure way to handle it. If I know somebody bought the book and know their email address, I can download the book as well. I think we can totally combine that mechanism with sending email to distribute the content.

**Comment by SaraVieira** [comment]
> Just wondering why you're hardcoding the Stripe API keys in the functions instead of using environment variables?
For some reason it wasn't working, have to fix that before merging

> It seems like you tried const info = require("../bookInfo") but then reverted back. What's the issue with it?
Netlify can't find the file so I reverted it and hardcoded, it may be because the functions are uploaded to lambda and the static files to S3

> Lastly, I finally understand what you meant by using email and check Stripe to verify that they're a customer. However, I think it's not the most secure way to handle it. If I know somebody bought the book and know their email address, I can download the book as well. I think we can totally combine that mechanism with sending email to distribute the content.

It would be awersome to send email with token

**Comment by SaraVieira** [comment]
Closing this as it's super old and really not relevant anymore in my opinion 

Feel free to restart it

**Pull request closed without merging**
